import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

interface ImageTag {
  tagId: string;
  tag: {
    id: string;
    name: string;
  };
}

interface LikedImage {
  id: string;
  imageTags: ImageTag[];
}

interface UserLike {
  userId: string;
  imageId: string;
  isLike: boolean;
  image: LikedImage;
}

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const userId = searchParams.get('userId');
    const limit = parseInt(searchParams.get('limit') || '6');

    if (!userId) {
      // If no user, return popular images
      const images = await prisma.image.findMany({
        orderBy: [
          { likeCount: 'desc' },
          { viewCount: 'desc' }
        ],
        take: limit,
      });

      return NextResponse.json({ images });
    }

    // Calculate limits for mixed content
    const autoLimit = Math.floor(limit / 2);
    // We'll calculate recLimit dynamically based on how many auto images we find
    
    // 1. Get user's recent autogenerated images
    const autoGeneratedImages = await prisma.image.findMany({
      where: {
        userId,
        description: {
          startsWith: 'Auto-generated image'
        }
      },
      orderBy: { createdAt: 'desc' },
      take: autoLimit
    });

    // 2. Calculate remaining slots for recommendations
    const effectiveRecLimit = limit - autoGeneratedImages.length;

    // Get tags from images the user has liked
    const userLikes = await prisma.like.findMany({
      where: {
        userId,
        isLike: true,
      },
      include: {
        image: {
          include: {
            imageTags: {
              include: {
                tag: true
              }
            }
          }
        }
      }
    }) as UserLike[];

    // Extract unique tag IDs from liked images
    const likedTagIds = new Set<string>();
    userLikes.forEach((like: UserLike) => {
      like.image.imageTags.forEach((imageTag: ImageTag) => {
        likedTagIds.add(imageTag.tagId);
      });
    });

    let recommendedImages: any[] = [];

    if (likedTagIds.size > 0) {
      // Find images with matching tags that the user hasn't uploaded
      // Use a deterministic ordering based on userId to ensure consistency
      const potentialRecommendations = await prisma.image.findMany({
        where: {
          userId: { not: userId },
          imageTags: {
            some: {
              tagId: { in: Array.from(likedTagIds) }
            }
          }
        },
        orderBy: [
          { likeCount: 'desc' },
          { createdAt: 'desc' },
          { id: 'asc' } // Add deterministic ordering
        ],
        take: effectiveRecLimit,
      });

      recommendedImages = potentialRecommendations;
    }

    // If we don't have enough recommendations, fill with popular images
    if (recommendedImages.length < effectiveRecLimit) {
      const additionalImages = await prisma.image.findMany({
        where: {
          userId: { not: userId },
          id: { notIn: recommendedImages.map((img) => img.id) }
        },
        orderBy: [
          { likeCount: 'desc' },
          { viewCount: 'desc' },
          { id: 'asc' } // Add deterministic ordering
        ],
        take: effectiveRecLimit - recommendedImages.length,
      });

      recommendedImages.push(...additionalImages);
    }

    // Combine images - interleave them for better display
    const finalImages: any[] = [];
    const maxLength = Math.max(autoGeneratedImages.length, recommendedImages.length);
    
    for (let i = 0; i < maxLength; i++) {
      if (i < recommendedImages.length) finalImages.push(recommendedImages[i]);
      if (i < autoGeneratedImages.length) finalImages.push(autoGeneratedImages[i]);
    }

    return NextResponse.json({ images: finalImages });
  } catch (error: any) {
    console.error('Error fetching recommended images:', error);
    return NextResponse.json(
      { message: 'Internal server error', error: error.message },
      { status: 500 }
    );
  }
}